---
latitude: 41.89672
longitude: -87.62507
map_zoom: 12
name: Park Hyatt - Chicago
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 800 N Michigan Ave
  street2: ''
  state: Illinois
  city: Chicago
  country: United States
  zip_code: '60611'
_hotel_id: PAR899
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
